### ISSUE TITLE
Generalizing NN for all cases

### ISSUE THREAD

**Issue by iok-ui** [giovannivolpe/BRAPH-2-Matlab-beta#154]
This issue requests the feature of implementing NN for other data cases (i.e. FUNCTIONAL, STRUCTURAL, STRUCTURAL MULTIMODALITY, CONNECTIVITY-FUNCTIONAL MULTIPLEX).

Get started with the following steps:
- Branch from develop.
- Create the new element file (e.g. _NNDataPoint_FUN_REG.gen.m),
- Run braph2genesis (needed only if and when new gen file is added), 
- Use tempNN.m to test your element, example script, or braph2 file, and
- Create a pull-request back to develop with requesting Yu-Wei's review, and
- Reqeust Giovanni's review after Yu-Wei tests it.

One can refer to the tentative [dev_nndatapoint.pdf](https://github.com/giovannivolpe/BRAPH-2-Matlab-beta/files/12599672/dev_nndatapoint.pdf) or [developer tutorial NN data point](https://github.com/giovannivolpe/BRAPH-2-Matlab-beta/pull/160) to generate the following NN elements, example scripts, and braph2 files: 

**FUNCTIONAL**
- [x] NNDataPoint_FUN_CLA (@bzufiriaki)
- [x] NNDataPoint_FUN_REG (@bzufiriaki)
- [x] example_NN_FUN_CLA(@bzufiriaki)
- [x] example_NN_FUN_REG (@bzufiriaki)
- [x] example_NNCV_FUN_WU_CLA(@bzufiriaki)
- [x] example_NNCV_FUN_BUD_REG (@bzufiriaki)
- [x] example_NNCV_FUN_BUT_REG (@bzufiriaki)
- [x] example_NNCV_FUN_WU_M_REG (@bzufiriaki)
- [x] example_NNCV_FUN_BUD_M_CLA(@bzufiriaki)
- [x] example_NNCV_FUN_BUT_M_CLA(@bzufiriaki)
- [x] pipeline_classification_training_test_split_functional_data.braph2(@bzufiriaki)
- [x] pipeline_regression_training_test_split_functional_data.braph2(@bzufiriaki)
- [x] pipeline_classification_cross_validation_functional_wu.braph2(@bzufiriaki)
- [x] pipeline_regression_cross_validation_functional_bud.braph2(@bzufiriaki)
- [x] pipeline_regression_cross_validation_functional_but.braph2(@bzufiriaki)
- [x] pipeline_regression_cross_validation_functional_wu_measure.braph2(@bzufiriaki)
- [x] pipeline_classification_cross_validation_functional_bud_measure.braph2(@bzufiriaki)
- [x] pipeline_classification_cross_validation_functional_but_measure.braph2(@bzufiriaki)

**STRUCTURAL**
- [x] NNDataPoint_ST_CLA (@JiaweiSun0512)
- [x] NNDataPoint_ST_REG (@JiaweiSun0512)
- [x] example_NN_ST_CLA  (@JiaweiSun0512)
- [x] example_NN_ST_REG (@JiaweiSun0512)
- [x] example_NNCV_ST_CLA  (@JiaweiSun0512)
- [x] example_NNCV_ST_REG (@JiaweiSun0512)
- [x] pipeline_classification_training_test_split_structural_data  (@JiaweiSun0512)
- [x] pipeline_regression_training_test_split_structural_data  (@JiaweiSun0512)
- [x] pipeline_classification_cross_validation_structural_data  (@JiaweiSun0512)
- [x] pipeline_regression_cross_validation_structural_data  (@JiaweiSun0512)

**STRUCTURAL MULTIMODALITY**
- [x] NNDataPoint_ST_MM_CLA  (@annacanal)
- [x] NNDataPoint_ST_MM_REG  (@annacanal)
- [x] example_NN_ST_MM_CLA  (@annacanal)
- [x] example_NN_ST_MM_REG  (@annacanal)
- [x] example_NNCV_ST_MM_CLA  (@annacanal)
- [x] example_NNCV_ST_MM_REG  (@annacanal)
- [x] pipeline_classification_training_test_split_structural_multimodality_data  (@annacanal)
- [x] pipeline_regression_training_test_split_structural_multimodality_data  (@annacanal)
- [x] pipeline_classification_cross_validation_structural_multimodality_data  (@annacanal)
- [x] pipeline_regression_cross_validation_structural_multimodality_data  (@annacanal)

**CONNECTIVITY-FUNCTIONAL MULTIPLEX**
- [x] NNDataPoint_CON_FUN_MP_CLA  (@annacanal)
- [x] NNDataPoint_CON_FUN_MP_REG (@annacanal)
- [x] example_NN_CON_FUN_MP_CLA (@annacanal)
- [x] example_NN_CON_FUN_MP_REG (@annacanal)
- [x] example_NNCV_CON_FUN_MP_WU_CLA (@annacanal)
- [x] example_NNCV_CON_FUN_MP_BUD_REG (@annacanal)
- [x] example_NNCV_CON_FUN_MP_BUT_REG (@annacanal)
- [x] example_NNCV_CON_FUN_MP_WU_M_REG (@annacanal)
- [x] example_NNCV_CON_FUN_MP_BUD_M_CLA (@annacanal)
- [x] example_NNCV_CON_FUN_MP_BUT_M_CLA (@annacanal)
- [x] pipeline_classification_training_test_split_connectivity_functional_multiplex_data.braph2 (@annacanal)
- [x] pipeline_regression_training_test_split_connectivity_functional_multiplex_data.braph2 (@annacanal)
- [x] pipeline_classification_cross_validation_connectivity_functional_multiplex_wu.braph2 (@annacanal)
- [x] pipeline_regression_cross_validation_connectivity_functional_multiplex_bud.braph2 (@annacanal)
- [x] pipeline_regression_cross_validation_connectivity_functional_multiplex_but.braph2 (@annacanal)
- [x] pipeline_regression_cross_validation_connectivity_functional_multiplex_wu_measure.braph2 (@annacanal)
- [x] pipeline_classification_cross_validation_connectivity_functional_multiplex_bud_measure.braph2 (@annacanal)
- [x] pipeline_classification_cross_validation_connectivity_functional_multiplex_but_measure.braph2 (@annacanal)

**Comment by c-yuwei** [comment]
[dev_nndatapoint.pdf](https://github.com/giovannivolpe/BRAPH-2-Matlab-beta/files/12599666/dev_nndatapoint.pdf)
This tentative version of tutorial for NNDataPoint should be helpful.
